################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# Configuration using monitor descriptions for static settings
# Main monitor configuration
monitor=desc:Dell Inc. Dell AW2521H,1920x1080@360,auto,1.0,bitdepth,10
monitor=desc:Samsung Electric Company LC34G55T HNTYB03454,3440x1440@165,auto,1.0,bitdepth,10


# Laptop monitor configuration
# Enabled
monitor=desc:AU Optronics B160UAN07.J,1920x1200@165.00,auto,1,bitdepth,10
# Disabled
# monitor=desc:AU Optronics B160UAN07.J,disabled

# Additional monitor configurations

# double monitor setup
monitor=desc:GIGA-BYTE TECHNOLOGY CO. LTD. GIGABYTE G24F,1920x1080@170,0x0,1.0,bitdepth,10
monitor=desc:ASUSTek COMPUTER INC ROG PG258Q,1920x1080@240,1920x0,1.0,bitdepth,10
