#############
## SUBMAPS ##
#############

$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, A, submap, resize
submap = resize
    # Arrow key window resizing 
    bind = CTRL, left, resizeactive, -10 0
    bind = CTRL, right, resizeactive, 10 0
    bind = CTRL, up, resizeactive, 0 -10
    bind = CTRL, down, resizeactive, 0 10
    bind = , escape, submap, reset
submap = reset
